set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

# Cross compilers to use for C, C++ and Fortran.

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_C_FLAGS_INIT "-D_WIN32_WINNT=0x600")
set(CMAKE_CXX_FLAGS_INIT "-D_WIN32_WINNT=0x600")

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_FIND_ROOT_PATH})
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_FIND_ROOT_PATH}/usr/lib/pkgconfig:${CMAKE_FIND_ROOT_PATH}/usr/share/pkgconfig")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(Vulkan_INCLUDE_DIR /usr/x86_64-w64-mingw32/sys-root/mingw/include/vulkan)
set(Vulkan_LIBRARY /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libvulkan-1.dll.a)

set(GLFW_BUILD_WIN32 ON)

set(GLFW_BUILD_X11 OFF)
set(GLFW_BUILD_WAYLAND OFF)